steps:
  - name: gcr.io/google.com/cloudsdk/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "Creating GCS bucket..."
        gcloud storage buckets create gs://${_BUCKET_NAME} \
          --location=${_BUCKET_LOCATION} \
          --storage-class=${_STORAGE_CLASS} \
          --project=${PROJECT_ID}
substitutions:
  _BUCKET_NAME: my-new-bucket-12345
  _BUCKET_LOCATION: US
  _STORAGE_CLASS: STANDARD
